//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemistryInfo.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChemistryInfoEntities : DbContext
    {
        private static ChemistryInfoEntities _context;

        public static ChemistryInfoEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ChemistryInfoEntities();
            }
            return _context;
        }

        public ChemistryInfoEntities()
            : base("name=ChemistryInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Elements> Elements { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Themes> Themes { get; set; }
    }
}
