//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemistryInfo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elements
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> AtomicNumber { get; set; }
        public Nullable<double> AtomicWeight { get; set; }
    }
}
